#!/usr/bin/env python3
"""Generate the PWA icon set and emit src/icons.ts with base64 PNGs.

Design: full-bleed ink background (#16161d), "JW" wordmark — J in white,
W in the brand purple (#a58bff) — matching the site header. Maskable
variant keeps the mark inside the 80% safe zone.
"""
import base64, io
from PIL import Image, ImageDraw, ImageFont

INK = (22, 22, 29, 255)
WHITE = (255, 255, 255, 255)
PURPLE = (165, 139, 255, 255)
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

def make(size: int, safe: float) -> bytes:
    img = Image.new("RGBA", (size, size), INK)
    d = ImageDraw.Draw(img)
    font = ImageFont.truetype(FONT, int(size * 0.42 * safe))
    j_box = d.textbbox((0, 0), "J", font=font)
    w_box = d.textbbox((0, 0), "W", font=font)
    total = (j_box[2] - j_box[0]) + (w_box[2] - w_box[0])
    x = (size - total) / 2 - j_box[0]
    y = (size - (j_box[3] - j_box[1])) / 2 - j_box[1]
    d.text((x, y), "J", font=font, fill=WHITE)
    d.text((x + (j_box[2] - j_box[0]), y), "W", font=font, fill=PURPLE)
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()

icons = {
    "180": make(180, 1.0),
    "192": make(192, 1.0),
    "512": make(512, 1.0),
    "maskable-512": make(512, 0.72),
}
with open("src/icons.ts", "w") as f:
    f.write("// Generated by scripts/make_icons.py — do not edit by hand.\n")
    f.write("export const ICON_PNGS: Record<string, string> = {\n")
    for name, data in icons.items():
        f.write(f"  '{name}':\n    '{base64.b64encode(data).decode()}',\n")
    f.write("};\n")
for name, data in icons.items():
    print(name, len(data), "bytes")
